/**
 * FraudTrace AI - Shared Constants & Epistemic Categorizations
 * Strictly Synthetic / Prototype Metadata Definitions
 */

export const EVIDENCE_CATEGORIES = {
  CHAT: 'Chat',
  SCREENSHOT: 'Screenshot',
  BANK_RECORD: 'Bank Record',
  EMAIL: 'Email',
  CALL_LOG: 'Call Log',
  TRANSACTION: 'Transaction',
  URL: 'URL',
  DOCUMENT: 'Document',
  OTHER: 'Other'
};

export const EVIDENCE_STATUSES = {
  UPLOADED: 'UPLOADED',
  PROCESSING: 'PROCESSING',
  EXTRACTED: 'EXTRACTED',
  CORRELATED: 'CORRELATED',
  REVIEW_REQUIRED: 'REVIEW REQUIRED'
};

export const ENTITY_TYPES = {
  PERSON: 'PERSON',
  PHONE: 'PHONE',
  EMAIL: 'EMAIL',
  URL: 'URL',
  TRANSACTION: 'TRANSACTION',
  PAYMENT_ID: 'PAYMENT_ID',
  BANK_ACCOUNT: 'BANK_ACCOUNT',
  UPI_ID: 'UPI_ID',
  LOCATION: 'LOCATION',
  ORGANIZATION: 'ORGANIZATION',
  DEVICE: 'DEVICE',
  DATE: 'DATE',
  TIME: 'TIME',
  AMOUNT: 'AMOUNT'
};

export const RELATIONSHIP_TYPES = {
  MENTIONED_IN: 'MENTIONED_IN',
  ASSOCIATED_WITH: 'ASSOCIATED_WITH',
  REFERENCES: 'REFERENCES',
  MATCHES: 'MATCHES',
  PRECEDES: 'PRECEDES',
  FOLLOWS: 'FOLLOWS',
  CONTAINS: 'CONTAINS',
  POSSIBLY_SAME_AS: 'POSSIBLY_SAME_AS',
  DERIVED_FROM: 'DERIVED_FROM',
  CORROBORATES: 'CORROBORATES',
  CONFLICTS_WITH: 'CONFLICTS_WITH'
};

export const INCONSISTENCY_TYPES = {
  AMOUNT_MISMATCH: 'AMOUNT_MISMATCH',
  TIMESTAMP_MISMATCH: 'TIMESTAMP_MISMATCH',
  DUPLICATE_RECORD: 'DUPLICATE_RECORD',
  CONFLICTING_IDENTIFIERS: 'CONFLICTING_IDENTIFIERS',
  MISSING_TRANSACTION_ID: 'MISSING_TRANSACTION_ID',
  UNMATCHED_TRANSACTION: 'UNMATCHED_TRANSACTION',
  CONFLICTING_ATTRIBUTES: 'CONFLICTING_ATTRIBUTES',
  BROKEN_RELATIONSHIP: 'BROKEN_RELATIONSHIP'
};

export const EPISTEMIC_TYPES = {
  FACT: 'FACT',
  EXTRACTED: 'EXTRACTED',
  CORRELATED: 'CORRELATED',
  INFERRED: 'INFERRED',
  CONFLICTING: 'CONFLICTING',
  MISSING: 'MISSING',
  REVIEW_REQUIRED: 'REVIEW REQUIRED'
};

export const SEVERITY_LEVELS = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL'
};

export const DEFAULT_CASE_ID = 'CASE-2026-001';
